org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

group = me.lukiiy
version = 1.0-SNAPSHOT
name = Lysten
id = lysten
authors = Lukiiy
description = A port of many client specific features to Fabric!
license = MIT

minecraft_version = 1.26.1.0
minecraft_version_range = [1.26.1.0,1.27)
neo_version = 26.1.0.19-beta
neo_version_range = [26,)
loader_version_range = [4,)